from pydantic import BaseModel

class HumanRequest(BaseModel):
    """
    @brief Represents a request from a human user containing a message.

    This model is used to validate and structure the input data
    received from the user, specifically the message they want to send.
    
    Attributes:
    - humanMessage (str): The message from the human user.
    """
    humanMessage: str

class AIResponse(BaseModel):
    """
    @brief Represents the response generated by the AI.

    This model is used to validate and structure the output data
    returned to the user, specifically the message generated by the AI.
    
    Attributes:
    - aiMessage (str): The response message generated by the AI.
    """
    aiMessage: str