# Configuration settings for the application
session_timeout: 3600 # Session timeout duration in seconds
db_max_table_limit: 5 # Maximum number of tables allowed in the database
max_file_limit: 5 # Maximum number of files allowed for uploads

llm_configs:
  sql_llm_model_name: gpt-4o-mini # Name of the LLM model
  embedding_model_name: text-embedding-3-large # Name of the embedding model
  llm_max_iteration: 10 # Maximum number of iterations for the LLM

end_points:
  signup: /signup # Endpoint for user signup
  login: /login # Endpoint for user login
  start_session: /start_session # Endpoint for starting a session
  check_session: /check_session # Endpoint for checking session status
  upload_csv: /upload_csv # Endpoint for uploading CSV files
  upload_pdf: /upload_pdf # Endpoint for uploading PDF files
  progress: /get_progress # Endpoint for checking progress
  sql_query: /sql_query # Endpoint for executing SQL queries
  rag_query: /rag_query # Endpoint for executing RAG queries
  clear_session: /clear_session # Endpoint for clearing a session
  end_session: /end_session # Endpoint for ending a session

server:
  sync_database_url: postgresql+psycopg2://qa:qa@172.20.0.23:5432 # URL for synchronous PostgreSQL database connection
  async_database_url: postgresql+asyncpg://qa:qa@172.20.0.23:5432 # URL for asynchronous PostgreSQL database connection
  user_database_name: user_db # Name of the user database (used for testing: test_user_db)
  redis_ip: 172.20.0.24 # IP address of the Redis server
  redis_port: 6379 # Port number for the Redis server
  app_ip: 0.0.0.0 # IP address for the application server (0.0.0.0 means it will listen on all interfaces)
  app_port: 8000 # Port number for the application server

paths:
  log_file_dir: "./.log/fastapi_app.log" # Directory for log files
  check_list:
    - ./.vector_stores # List of directories to check
    - ./.log # Log directory
  origin_list:
    - "http://localhost:3000" # Allowed origin for CORS (local development)
    - "http://localhost:8000" # Allowed origin for CORS (local development)
    - "http://172.20.0.22:3000" # Allowed origin for CORS (remote development)
    - "http://172.20.0.22:8000" # Allowed origin for CORS (remote development)