CREATE USER qa WITH ENCRYPTED PASSWORD 'qa';

\c user_db;

CREATE DATABASE IF NOT EXISTS user_db;

GRANT ALL PRIVILEGES ON DATABASE user_db TO qa;

CREATE TABLE IF NOT EXISTS "User" (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL
);
